### ISSUE TITLE
Topshelf Username

### ISSUE THREAD

**Issue by Boggyboy** [bcowdery/octopus-scripts#3]
How can I add the service username and password to the Topshelf Service script for Octopus?

**Comment by bcowdery** [comment]
Topshelf docs:
http://docs.topshelf-project.com/en/latest/overview/commandline.html

You should be able to append `-username` and `-password` to the installer string at line 26

https://github.com/bcowdery/octopus-scripts/blob/master/topshelf/Deploy.ps1#L26

**Comment by Boggyboy** [comment]
Thanks!
